In [120]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [121]:
df = pd.read_csv('voos.csv', sep=';', header=1)
df.head()

,Data Referência UTC,Sigla ICAO Empresa Aérea,Nome da Empresa Aérea,Número Etapa,Número Voo,Sigla ICAO Modelo Aeronave,Quantidade de Assentos Previstos,Sigla ICAO Aeroporto Origem,Data Partida Prevista UTC,Sigla ICAO Aeroporto Destino,Data Chegada Prevista UTC,Tipo de Voo
0,01/12/2025 00:00:00,1ED,SERVICIOS AÉREOS PANAMERICANOS LTDA. SARPA S.A.S,1,3304,E145,50,SBEG,01/12/2025 00:50:00,SKBO,01/12/2025 03:45:00,NÃO REGULAR DE PASSAGEIROS INTERNACIONAL
1,01/12/2025 00:00:00,AAL,"AMERICAN AIRLINES, INC.",1,0904,B772,288,SBGL,01/12/2025 02:55:00,KMIA,01/12/2025 11:40:00,REGULAR DE PASSAGEIROS INTERNACIONAL
2,01/12/2025 00:00:00,AAL,"AMERICAN AIRLINES, INC.",1,0905,B772,288,KMIA,01/12/2025 04:00:00,SBGL,01/12/2025 12:25:00,REGULAR DE PASSAGEIROS INTERNACIONAL
3,01/12/2025 00:00:00,AAL,"AMERICAN AIRLINES, INC.",1,0906,B788,295,SBGR,01/12/2025 03:15:00,KMIA,01/12/2025 11:35:00,REGULAR DE PASSAGEIROS INTERNACIONAL
4,01/12/2025 00:00:00,AAL,"AMERICAN AIRLINES, INC.",1,0925,B788,295,KMIA,01/12/2025 03:35:00,SBGR,01/12/2025 11:50:00,REGULAR DE PASSAGEIROS INTERNACIONAL

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 920477 entries, 0 to 920476
Data columns (total 12 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Data Referência UTC               920477 non-null  str
 1   Sigla ICAO Empresa Aérea          920477 non-null  str
 2   Nome da Empresa Aérea             920477 non-null  str
 3   Número Etapa                      920477 non-null  int64
 4   Número Voo                        920477 non-null  str
 5   Sigla ICAO Modelo Aeronave        920477 non-null  str
 6   Quantidade de Assentos Previstos  920477 non-null  int64
 7   Sigla ICAO Aeroporto Origem       920477 non-null  str
 8   Data Partida Prevista UTC         920477 non-null  str
 9   Sigla ICAO Aeroporto Destino      920477 non-null  str
 10  Data Chegada Prevista UTC         920477 non-null  str
 11  Tipo de Voo                       920477 non-null  str
dtypes: int64(2), str(10)
memory usage: 84.3 MB

In [123]:
df['Data Referência UTC'] = pd.to_datetime(df['Data Referência UTC'], errors='coerce')
df['Data Partida Prevista UTC'] = pd.to_datetime(df['Data Partida Prevista UTC'], errors='coerce')
df['Data Chegada Prevista UTC'] = pd.to_datetime(df['Data Chegada Prevista UTC'], errors='coerce')

In [124]:
df['Número Etapa'] = df['Número Etapa'].astype(int)
df['Quantidade de Assentos Previstos'] = df['Quantidade de Assentos Previstos'].astype(int)

In [125]:
df['Data Referência UTC'].value_counts()

Data Referência UTC
2025-01-12    3050
2026-08-01    3046
2025-04-12    3044
2026-05-01    3044
2025-08-12    3042
              ...
2026-01-12     831
2026-02-12     826
2026-07-11     762
2026-01-11     745
2026-08-11     745
Name: count, Length: 146, dtype: int64

In [126]:
df_eda = df[
    (df['Data Referência UTC'] < '2026-01-01') |
    (df['Data Referência UTC'] > '2025-01-01')
    ].copy()
df_eda.shape

(372751, 12)

In [127]:
df_eda['Tipo de Voo'].value_counts()

Tipo de Voo
REGULAR DE PASSAGEIROS DOMÉSTICA                     302757
REGULAR DE PASSAGEIROS INTERNACIONAL                  57579
SOBREVOOS OU TRASLADOS OPERACIONAIS INTERNACIONAL      6096
REGULAR DE CARGA DOMÉSTICA                             3380
REGULAR DE CARGA INTERNACIONAL                         1812
NÃO REGULAR DE PASSAGEIROS DOMÉSTICA                    375
NÃO REGULAR DE CARGA DOMÉSTICA                          352
REGULAR DE CARGA DE CORREIO DOMÉSTICA                   198
NÃO REGULAR DE PASSAGEIROS INTERNACIONAL                166
SOBREVOOS OU TRASLADOS OPERACIONAIS DOMÉSTICA            23
NÃO REGULAR DE CARGA INTERNACIONAL                        9
REGULAR DE CARGA OU CORREIO INTERNACIONAL                 4
Name: count, dtype: int64

In [128]:
df_eda = df_eda[df_eda['Tipo de Voo'] == 'REGULAR DE PASSAGEIROS DOMÉSTICA']

In [129]:
df_pub = pd.read_csv('AerodromosPublicos.csv', sep=';', header=1)
df_pub.columns

Index(['CÓDIGO OACI', 'CIAD', 'NOME', 'MUNICÍPIO ATENDIDO', 'UF', 'LATITUDE',
       'LONGITUDE', 'ALTITUDE', 'OPERAÇÃO', 'OACI', 'AIP BRASIL', 'DESIGNAÇÃO',
       'COMPRIMENTO', 'LARGURA', 'RESISTÊNCIA', 'SUPERFÍCIE', 'DESIGNAÇÃO.1',
       'COMPRIMENTO.1', 'LARGURA.1', 'RESISTÊNCIA.1', 'SUPERFÍCIE.1',
       'DESIGNAÇÃO.2', 'COMPRIMENTO.2', 'LARGURA.2', 'RESISTÊNCIA.2',
       'SUPERFÍCIE.2', 'RAMPA(S) DE APROXIMAÇÃO', 'FORMATO DA ÁREA DE POUSO',
       'DIMENSÕES', 'RESISTÊNCIA.3', 'SUPERFÍCIE.3', 'p1', 'p2', 'p3', 'p4',
       'PORTARIAS', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'PORTARIA Nº 16.739/2025 e alterações',
       'Portaria nº 17.388/2025\nA Classe I se divide ainda em RBAC 121, RBAC 135 Regular e Outras Operações',
       'PORTARIA Nº 2007/2014 E ALTERAÇÕES\n(* = REGIME TARIFÁRIO DIFERENCIADO)',
       'AERONAVE CRÍTICA', 'TIPO DE APROX. (CABECEIRAS)', 'CAT SESCINC', 'r1',
       'r2', 'REFERÊNCIA(S)', 'RESTRIÇÃO(ÕES)', 'SITUAÇÃO', 'r1.1',
       'REFERÊNCIA', 'SITUADO NA AMAZÔNIA LEGAL', 'OBSERVAÇÕES'],
      dtype='str')

In [130]:
df_pub_origem = df_pub.rename(columns={
    'CÓDIGO OACI': 'origem_icao',
    'MUNICÍPIO ATENDIDO': 'origem_cidade',
    'UF': 'origem_uf',
    'LATITUDE': 'origem_lat',
    'LONGITUDE': 'origem_lon',
    'ALTITUDE': 'origem_alt'
})
df_pub_destino = df_pub.rename(columns={
    'CÓDIGO OACI': 'destino_icao',
    'MUNICÍPIO ATENDIDO': 'destino_cidade',
    'UF': 'destino_uf',
    'LATITUDE': 'destino_lat',
    'LONGITUDE': 'destino_lon',
    'ALTITUDE': 'destino_alt'
})

In [131]:
df_eda = pd.merge(
    df_eda,
    df_pub_origem[['origem_icao', 'origem_cidade', 'origem_uf', 'origem_lat', 'origem_lon', 'origem_alt']],
    left_on='Sigla ICAO Aeroporto Origem',
    right_on='origem_icao',
    how='left'
)

In [132]:
df_eda = pd.merge(
    df_eda,
    df_pub_destino[['destino_icao', 'destino_cidade', 'destino_uf', 'destino_lat', 'destino_lon', 'destino_alt']],
    left_on='Sigla ICAO Aeroporto Destino',
    right_on='destino_icao',
    how='left'
)
df_eda.head()

,Data Referência UTC,Sigla ICAO Empresa Aérea,Nome da Empresa Aérea,Número Etapa,Número Voo,Sigla ICAO Modelo Aeronave,Quantidade de Assentos Previstos,Sigla ICAO Aeroporto Origem,Data Partida Prevista UTC,Sigla ICAO Aeroporto Destino,Data Chegada Prevista UTC,Tipo de Voo,origem_icao,origem_cidade,origem_uf,origem_lat,origem_lon,origem_alt,destino_icao,destino_cidade,destino_uf,destino_lat,destino_lon,destino_alt
0,2025-01-12,ABJ,ATA - AEROTÁXI ABAETÉ LTDA.,1,1406,C208,9,SBSV,2025-01-12 16:00:00,SNCL,2025-01-12 16:30:00,REGULAR DE PASSAGEIROS DOMÉSTICA,SBSV,SALVADOR,BA,12° 54' 31'' S,38° 19' 21'' W,20 m,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-12,ABJ,ATA - AEROTÁXI ABAETÉ LTDA.,1,1407,C208,9,SNCL,2025-01-12 16:45:00,SBSV,2025-01-12 17:15:00,REGULAR DE PASSAGEIROS DOMÉSTICA,NaN,NaN,NaN,NaN,NaN,NaN,SBSV,SALVADOR,BA,12° 54' 31'' S,38° 19' 21'' W,20 m
2,2025-01-12,ABJ,ATA - AEROTÁXI ABAETÉ LTDA.,1,1408,C208,9,SBSV,2025-01-12 17:45:00,SNCL,2025-01-12 18:15:00,REGULAR DE PASSAGEIROS DOMÉSTICA,SBSV,SALVADOR,BA,12° 54' 31'' S,38° 19' 21'' W,20 m,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-01-12,ABJ,ATA - AEROTÁXI ABAETÉ LTDA.,1,1409,C208,9,SDLO,2025-01-12 19:00:00,SBSV,2025-01-12 19:35:00,REGULAR DE PASSAGEIROS DOMÉSTICA,NaN,NaN,NaN,NaN,NaN,NaN,SBSV,SALVADOR,BA,12° 54' 31'' S,38° 19' 21'' W,20 m
4,2025-01-12,ABJ,ATA - AEROTÁXI ABAETÉ LTDA.,2,Z1408,C208,9,SNCL,2025-01-12 18:30:00,SDLO,2025-01-12 18:45:00,REGULAR DE PASSAGEIROS DOMÉSTICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [133]:
df_eda = df_eda.dropna()
df_eda.info()

<class 'pandas.DataFrame'>
Index: 300083 entries, 5 to 302756
Data columns (total 24 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Data Referência UTC               300083 non-null  datetime64[us]
 1   Sigla ICAO Empresa Aérea          300083 non-null  str
 2   Nome da Empresa Aérea             300083 non-null  str
 3   Número Etapa                      300083 non-null  int64
 4   Número Voo                        300083 non-null  str
 5   Sigla ICAO Modelo Aeronave        300083 non-null  str
 6   Quantidade de Assentos Previstos  300083 non-null  int64
 7   Sigla ICAO Aeroporto Origem       300083 non-null  str
 8   Data Partida Prevista UTC         300083 non-null  datetime64[us]
 9   Sigla ICAO Aeroporto Destino      300083 non-null  str
 10  Data Chegada Prevista UTC         300083 non-null  datetime64[us]
 11  Tipo de Voo                       300083 non-null  str
 12  origem_icao                       300083 non-null  str
 13  origem_cidade                     300083 non-null  str
 14  origem_uf                         300083 non-null  str
 15  origem_lat                        300083 non-null  str
 16  origem_lon                        300083 non-null  str
 17  origem_alt                        300083 non-null  str
 18  destino_icao                      300083 non-null  str
 19  destino_cidade                    300083 non-null  str
 20  destino_uf                        300083 non-null  str
 21  destino_lat                       300083 non-null  str
 22  destino_lon                       300083 non-null  str
 23  destino_alt                       300083 non-null  str
dtypes: datetime64[us](3), int64(2), str(19)
memory usage: 57.2 MB

In [134]:
df_eda.head()

,Data Referência UTC,Sigla ICAO Empresa Aérea,Nome da Empresa Aérea,Número Etapa,Número Voo,Sigla ICAO Modelo Aeronave,Quantidade de Assentos Previstos,Sigla ICAO Aeroporto Origem,Data Partida Prevista UTC,Sigla ICAO Aeroporto Destino,Data Chegada Prevista UTC,Tipo de Voo,origem_icao,origem_cidade,origem_uf,origem_lat,origem_lon,origem_alt,destino_icao,destino_cidade,destino_uf,destino_lat,destino_lon,destino_alt
5,2025-01-12,ACN,AZUL CONECTA LTDA. (EX TWO TAXI AEREO LTDA),1,5108,C208,9,SBBE,2025-01-12 15:30:00,SBCJ,2025-01-12 17:50:00,REGULAR DE PASSAGEIROS DOMÉSTICA,SBBE,BELÉM,PA,1° 23' 5'' S,48° 28' 44'' W,17 m,SBCJ,PARAUAPEBAS,PA,6° 7' 4'' S,50° 0' 12'' W,629 m
6,2025-01-12,ACN,AZUL CONECTA LTDA. (EX TWO TAXI AEREO LTDA),1,5109,C208,9,SBCJ,2025-01-12 20:55:00,SBBE,2025-01-12 23:15:00,REGULAR DE PASSAGEIROS DOMÉSTICA,SBCJ,PARAUAPEBAS,PA,6° 7' 4'' S,50° 0' 12'' W,629 m,SBBE,BELÉM,PA,1° 23' 5'' S,48° 28' 44'' W,17 m
7,2025-01-12,ACN,AZUL CONECTA LTDA. (EX TWO TAXI AEREO LTDA),1,5110,C208,9,SBCJ,2025-01-12 18:25:00,SDOW,2025-01-12 19:10:00,REGULAR DE PASSAGEIROS DOMÉSTICA,SBCJ,PARAUAPEBAS,PA,6° 7' 4'' S,50° 0' 12'' W,629 m,SDOW,OURILÂNDIA DO NORTE,PA,6° 45' 47'' S,51° 2' 60'' W,229 m
8,2025-01-12,ACN,AZUL CONECTA LTDA. (EX TWO TAXI AEREO LTDA),1,5111,C208,9,SDOW,2025-01-12 19:35:00,SBCJ,2025-01-12 20:20:00,REGULAR DE PASSAGEIROS DOMÉSTICA,SDOW,OURILÂNDIA DO NORTE,PA,6° 45' 47'' S,51° 2' 60'' W,229 m,SBCJ,PARAUAPEBAS,PA,6° 7' 4'' S,50° 0' 12'' W,629 m
9,2025-01-12,ACN,AZUL CONECTA LTDA. (EX TWO TAXI AEREO LTDA),1,5112,C208,9,SBCF,2025-01-12 17:25:00,SNSS,2025-01-12 19:15:00,REGULAR DE PASSAGEIROS DOMÉSTICA,SBCF,BELO HORIZONTE,MG,19° 37' 28'' S,43° 58' 19'' W,829 m,SNSS,SALINAS,MG,16° 12' 30'' S,42° 19' 19'' W,763 m